name = "specimen"
version = "0.1.0"
defaultTargets = ["Specimen"]
testRunner = "SpecimenTest"
lintDriver = "batteries/runLinter"

[leanOptions]
linter.missingDocs = false

[[lean_lib]]
name = "SpecimenTest"

[[lean_lib]]
name = "Specimen"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "9acabf83fb0369d00ba2e2410ca68db581a96bcc"

[[require]]
name = "plausible"
scope = "leanprover-community"
rev = "264309b5c0c10e569025a53ab6440a45c03133e4"

[[require]]
name = "proofwidgets"
scope = "leanprover-community"
rev = "v0.0.96"